### ISSUE TITLE
pylonGPS still active ?

### ISSUE THREAD

**Issue by ccmsi** [charlesrwest/pylonGPS#2]
Greetings.
I wanted to know if this repository / project is still active.
Thanks.

**Comment by charlesrwest** [comment]
Hello,

As far as I know the server is still running.  I haven't worked on the
project in a while because I didn't get much indication of interest.  If
you have a specific problem you are working on or need help getting it
setup, please let me know.

Thanks,
Charlie West

**Comment by ccmsi** [comment]
As the reply by email doesnt show up, i'm copying it in...

Greetings Mr West.
Indeed the service seems up right now. When i tried about 3 or 4 weeks ago, it seemed to be down though, so for the moment i have set an additional one up.

I'm currently working on integrating a set of open source components into a ready to run installation to make it easy to join into a network with ones own basestation.
I'm using PylonGPS as the networking component for this. The project is described at http://docs.navdata.net/en/latest/about.html#current-goal

I have some questions regarding PylonGPS.

When starting the transceiver for streaming data to the caster, one provides the stations location Latitude and Longitude for querying. It appears for a receiving user, the station static height information, apart from the data stream content, might also be of interest to allow the receiving side to configure accordingly. Would such an addition in commandline options and caster data / indexing, together with the retrievers querying / listing be of interest to implement ?

Is the windows version of transceiver / transceiverGUI intended to be implemented ?

Would additional platforms be considered (eg Android) ?

For a community caster, which allows unregistered connection without issued keyes, it seems useful to reduce the value for abuse. While having no actual solution, i'm thinking of options such as ratelimiting traffic per IP.

I'm trying to allow different streams from the same base, therefore from the exact same location, running more than one instance of uploading transceiver. I'm having problems selecting a specific one in the transceiverGUI, such that i can only access one, not the other.

I have created two patches, which i needed for crosscompiling and staging to work for PylonGPS. One of them may need a change to populate the bin folder with the shared libraries if the intention is to run the binaries from the source folder without installation in system folders. I havent tested them outside of cross compiling yet, but would like to know if you would consider such once verified. In their current state, they are at:
https://raw.githubusercontent.com/navdata-net/meta-navdatanet/rocko/recipes-gnss/pylongps/files/fixes.patch
and
https://raw.githubusercontent.com/navdata-net/meta-navdatanet/rocko/recipes-gnss/pylongps/files/yocto.patch
respectively.

Thanks and best regards.
Michael

**Comment by ccmsi** [comment]
I realized, i missed to mention one feature request that seems rather important to me.

For configuring the transceiver as a service, it would be advantageous to have an alternative means for providing configuration, ie as configuration file. The intention being to allow for updates of the location without changing the service definition, which would be necessary for commandline only options.

In my specific case, i will be updating / adjusting the location regularily (eg, once a day) which would fits well with a configuration file update and restart of the service (or HUP signal?). Apart from that I could imagine mobile use cases though, where it would be advantageous to allow for continuous updates to the running process, ie through one of its ports or a unix socket.

**Comment by charlesrwest** [comment]
OK.  Your intended use case appears to be directly in line with what PylonGPS was designed to facilitate, so lets make this happen.  I am under heavy work load right now and will continue to be until the end of the month, so we might have to hold off on major changes till then.  

In the mean time:
I set the server going when I completed the draft of this project for my master's thesis and haven't really touched it since.  It is setup to automatically restart if the virtual server it is being hosted on goes down for any reason, but I haven't observed it going down so far.  If you spot it being down again, please let me know.  If I get spare time, I will make an analysis program to measure down time (sending a dummy stream and logging if it hiccups).

Adding height as a field would require digging into the SQL and the database format.  Depending on how I formated it that should either be 4-8 hrs of work or considerably more.  Are you sure it is needed?

If there is sufficient interest, I would be happy to provide a windows port.  CMake has some nice options for creating installers.  Most of the code is based on reasonably portable libraries, so other platforms could be doable.  That said, it would probably make the most sense to start with an Ubuntu .deb

That is a valid point.  It was not implemented originally because it was not known how big the streams would be (protocol agnostic).  However, rate limiting could be simple to implement if ZMQ supports it.  I'll have to check with the ZMQ docs to see.

Could you give more details about the GUI problem (step by step, so I can reproduce it?).

I will try to take a look at the patches this weekend.  Thank you!

As I recall, the transceiver GUI can make configuration files for later re-loading.  I believe that was implemented as a binary protobuf object (which means you could write one with the protobuf library) but it could be feasible to make a JSON version as well.

**Comment by ccmsi** [comment]
Height:
This can be deferred. The background is that each rtklib uses it for starting their str2str, similar to transceiver. So if that can be fetched from pylon, then str2str can be started accordingly as a 2nd stage. Also i believe, not know, this is how rtklib gets the defined/verified/true location of the base, as this is not part of the streamed data, but is there to optionally be defined in rtklib resolver with the basestation data source. I assume, instead of defining it at the client, the configuration from the serverside provided with str2str can be used. It would complicated to organize otherwise.
As an easy workaround for now, i should be able to use the station name to provide the height.

By using the keyword "DB" you brought up a different idea though, which may be sth for later. If there was a possibility to hook up pylongps to 1 table of a database, all columns of which can be readonly queried by clients with a command in the connection that can lookup nearby stations stations, then pylongps server admins have a way of providing added functionality. Ie, their service can define fields with statistical data for the stations such as stream availability, total runtime, data quality, ratings, email contacts... whatever their pleasure, without the need to change pylongps server.

At the moment, i'm more concerned with the binary configuration. The operational environment is built with an IoT kind of linux environment, trying to keep it slim and stitching things together with shell scripts and a basic set of system tools, adding what is needed but aiming for a small footprint. What tools would you recommend to compile the configuration in such a setting ?

**Comment by ccmsi** [comment]
On the caster side i notice that the connection IDs increment, as it appears, for every reconnect of a client (simply, for every new connection i guess). As i'll have the transceivers update their location by reconnecting and assuming a growing number of clients, what happens on an overflow ?
While at it, the possibility to "gate" transceivers from the server side would be interesting. For example we have a community base with bad reception, after each restart, it will take a while for it settle. Server side could implement a gate function for this and other cases that makes an uploading transceiver invisible to other clients unless certain conditions are met. Ideally from outside logic, sending enable / disable commands, to allow different users with different patterns.
